[pytest]
pythonpath = .
DJANGO_SETTINGS_MODULE=tests.settings
addopts = --cov=django_pickling --cov-report=term-missing --cov-branch
filterwarnings =
    error
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning

